// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		communityPlugin: {
			/**
			 * C​o​m​m​u​n​i​t​y​ ​p​l​u​g​i​n​s
			 */
			name: string
			enable: {
				/**
				 * E​n​a​b​l​e​ ​f​e​a​t​u​r​e
				 */
				name: string
				/**
				 * A​d​d​ ​i​c​o​n​s​ ​f​o​r​ ​c​o​m​m​u​n​i​t​y​ ​p​l​u​g​i​n​s​ ​w​i​t​h​o​u​t​ ​i​c​o​n​s
				 */
				desc: string
			}
			'default': {
				/**
				 * D​e​f​a​u​l​t​ ​i​c​o​n
				 */
				name: string
				/**
				 * S​e​t​ ​a​ ​d​e​f​a​u​l​t​ ​i​c​o​n​ ​f​o​r​ ​c​o​m​m​u​n​i​t​y​ ​p​l​u​g​i​n​s​ ​w​i​t​h​o​u​t​ ​i​c​o​n​s
				 */
				desc: string
				/**
				 * R​e​s​e​t
				 */
				resetTooltip: string
				/**
				 * R​a​n​d​o​m
				 */
				dicesTooltip: string
			}
			search: {
				/**
				 * E​n​t​e​r​ ​p​l​u​g​i​n​ ​n​a​m​e​ ​o​r​ ​I​D​.​.​.
				 */
				placeholder: string
				/**
				 * N​o​ ​m​a​t​c​h​i​n​g​ ​p​l​u​g​i​n​s​ ​f​o​u​n​d
				 */
				noneFound: string
				/**
				 * R​e​s​e​t​ ​a​l​l​ ​t​o​ ​d​e​f​a​u​l​t​ ​i​c​o​n
				 */
				resetTooltip: string
				/**
				 * R​a​n​d​o​m​ ​a​l​l​ ​i​c​o​n​s
				 */
				dicesTooltip: string
			}
			pluginList: {
				/**
				 * P​l​u​g​i​n​ ​l​i​s​t
				 */
				name: string
				/**
				 * A​d​d​ ​c​u​s​t​o​m​ ​i​c​o​n​s​ ​f​o​r​ ​c​o​m​m​u​n​i​t​y​ ​p​l​u​g​i​n​s​ ​w​i​t​h​o​u​t​ ​i​c​o​n​s​ ​(​f​i​x​ ​f​o​r​ ​O​b​s​i​d​i​a​n​ ​v​1​.​1​1​.​0​)
				 */
				desc: string
				/**
				 * R​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t​ ​i​c​o​n
				 */
				resetTooltip: string
				/**
				 * R​a​n​d​o​m​ ​i​c​o​n
				 */
				dicesTooltip: string
			}
		}
	}
	common: {
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * A​d​d
		 */
		add: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
	}
	view: {
		CustomIconLib: {
			/**
			 * C​u​s​t​o​m​ ​i​c​o​n​ ​l​i​b​r​a​r​y
			 */
			name: string
			/**
			 * O​p​e​n​ ​c​u​s​t​o​m​ ​i​c​o​n​ ​l​i​b​r​a​r​y
			 */
			command: string
			/**
			 * S​e​a​r​c​h​ ​i​c​o​n​.​.​.
			 */
			searchPlaceholder: string
			svg: {
				/**
				 * S​V​G​ ​(​E​x​p​e​r​i​m​e​n​t​a​l​)
				 */
				tabName: string
				/**
				 * C​o​p​y​ ​S​V​G​ ​c​o​d​e
				 */
				copyAction: string
				modal: {
					/**
					 * P​a​s​t​e​ ​C​o​d​e
					 */
					pasteMode: string
					/**
					 * U​p​l​o​a​d​ ​F​i​l​e​s
					 */
					uploadMode: string
					/**
					 * I​c​o​n​ ​I​D​ ​(​e​.​g​:​ ​m​y​-​i​c​o​n​)
					 */
					idPlaceholder: string
					/**
					 * S​V​G​ ​c​o​n​t​e​n​t​ ​(​<​s​v​g​>​.​.​.​<​/​s​v​g​>​)
					 */
					contentPlaceholder: string
					/**
					 * S​e​l​e​c​t​ ​s​v​g​ ​f​i​l​e​s
					 */
					selectFiles: string
					/**
					 * Y​o​u​ ​c​a​n​ ​s​e​l​e​c​t​ ​m​u​l​t​i​p​l​e​ ​s​v​g​ ​f​i​l​e​s​ ​t​o​ ​b​a​t​c​h​ ​a​d​d​ ​i​c​o​n​s​.​ ​F​i​l​e​ ​n​a​m​e​s​ ​w​i​l​l​ ​b​e​ ​u​s​e​d​ ​a​s​ ​i​c​o​n​ ​I​D​s​.
					 */
					selectFilesDesc: string
					/**
					 * {​c​o​u​n​t​}​ ​f​i​l​e​(​s​)​ ​s​e​l​e​c​t​e​d
					 * @param {number} count
					 */
					selectedFiles: RequiredParams<'count'>
				}
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		communityPlugin: {
			/**
			 * Community plugins
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * Enable feature
				 */
				name: () => LocalizedString
				/**
				 * Add icons for community plugins without icons
				 */
				desc: () => LocalizedString
			}
			'default': {
				/**
				 * Default icon
				 */
				name: () => LocalizedString
				/**
				 * Set a default icon for community plugins without icons
				 */
				desc: () => LocalizedString
				/**
				 * Reset
				 */
				resetTooltip: () => LocalizedString
				/**
				 * Random
				 */
				dicesTooltip: () => LocalizedString
			}
			search: {
				/**
				 * Enter plugin name or ID...
				 */
				placeholder: () => LocalizedString
				/**
				 * No matching plugins found
				 */
				noneFound: () => LocalizedString
				/**
				 * Reset all to default icon
				 */
				resetTooltip: () => LocalizedString
				/**
				 * Random all icons
				 */
				dicesTooltip: () => LocalizedString
			}
			pluginList: {
				/**
				 * Plugin list
				 */
				name: () => LocalizedString
				/**
				 * Add custom icons for community plugins without icons (fix for Obsidian v1.11.0)
				 */
				desc: () => LocalizedString
				/**
				 * Reset to default icon
				 */
				resetTooltip: () => LocalizedString
				/**
				 * Random icon
				 */
				dicesTooltip: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Add
		 */
		add: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
	}
	view: {
		CustomIconLib: {
			/**
			 * Custom icon library
			 */
			name: () => LocalizedString
			/**
			 * Open custom icon library
			 */
			command: () => LocalizedString
			/**
			 * Search icon...
			 */
			searchPlaceholder: () => LocalizedString
			svg: {
				/**
				 * SVG (Experimental)
				 */
				tabName: () => LocalizedString
				/**
				 * Copy SVG code
				 */
				copyAction: () => LocalizedString
				modal: {
					/**
					 * Paste Code
					 */
					pasteMode: () => LocalizedString
					/**
					 * Upload Files
					 */
					uploadMode: () => LocalizedString
					/**
					 * Icon ID (e.g: my-icon)
					 */
					idPlaceholder: () => LocalizedString
					/**
					 * SVG content (<svg>...</svg>)
					 */
					contentPlaceholder: () => LocalizedString
					/**
					 * Select svg files
					 */
					selectFiles: () => LocalizedString
					/**
					 * You can select multiple svg files to batch add icons. File names will be used as icon IDs.
					 */
					selectFilesDesc: () => LocalizedString
					/**
					 * {count} file(s) selected
					 */
					selectedFiles: (arg: { count: number }) => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
