// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'
	| 'zh-TW'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		communityPlugin: {
			/**
			 * 第​三​方​插​件
			 */
			name: string
			enable: {
				/**
				 * 启​用​功​能
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​图​标
				 */
				desc: string
			}
			'default': {
				/**
				 * 默​认​图​标
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​设​置​添​加​默​认​图​标
				 */
				desc: string
				/**
				 * 重​置
				 */
				resetTooltip: string
				/**
				 * 随​机
				 */
				dicesTooltip: string
			}
			search: {
				/**
				 * 输​入​插​件​名​称​.​.​.
				 */
				placeholder: string
				/**
				 * 未​找​到​匹​配​的​插​件
				 */
				noneFound: string
				/**
				 * 重​置​所​有​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​所​有​图​标
				 */
				dicesTooltip: string
			}
			pluginList: {
				/**
				 * 插​件​列​表
				 */
				name: string
				/**
				 * 为​没​有​图​标​的​第​三​方​插​件​添​加​自​定​义​图​标​（​修​复​ ​O​b​s​i​d​i​a​n​ ​v​1​.​1​1​.​0​）
				 */
				desc: string
				/**
				 * 重​置​为​默​认​图​标
				 */
				resetTooltip: string
				/**
				 * 随​机​图​标
				 */
				dicesTooltip: string
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		communityPlugin: {
			/**
			 * 第三方插件
			 */
			name: () => LocalizedString
			enable: {
				/**
				 * 启用功能
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加图标
				 */
				desc: () => LocalizedString
			}
			'default': {
				/**
				 * 默认图标
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件设置添加默认图标
				 */
				desc: () => LocalizedString
				/**
				 * 重置
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机
				 */
				dicesTooltip: () => LocalizedString
			}
			search: {
				/**
				 * 输入插件名称...
				 */
				placeholder: () => LocalizedString
				/**
				 * 未找到匹配的插件
				 */
				noneFound: () => LocalizedString
				/**
				 * 重置所有为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机所有图标
				 */
				dicesTooltip: () => LocalizedString
			}
			pluginList: {
				/**
				 * 插件列表
				 */
				name: () => LocalizedString
				/**
				 * 为没有图标的第三方插件添加自定义图标（修复 Obsidian v1.11.0）
				 */
				desc: () => LocalizedString
				/**
				 * 重置为默认图标
				 */
				resetTooltip: () => LocalizedString
				/**
				 * 随机图标
				 */
				dicesTooltip: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
